repos:
  - repo: local
    hooks:
      - id: terraform-fmt-check
        name: terraform fmt (check)
        entry: terraform fmt -recursive -check
        language: system
        files: "\\.tf$"
        stages: [pre-push]
