name: Terraform Clean workflow

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: readG
    defaults:
      run:
        working-directory: ./infra
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_base_url: ${{ secrets.BASE_URL }}
      TF_VAR_vpc_cidr: ${{ secrets.VPC_CIDR }}
      TF_VAR_primary_subnet_cidr: ${{ secrets.PRIMARY_SUBNET_CIDR }}
      TF_VAR_secondary_subnet_cidr: ${{ secrets.SECONDARY_SUBNET_CIDR }}
      TF_VAR_private_subnet_1_cidr: ${{ secrets.PRIVATE_SUBNET_1_CIDR }}
      TF_VAR_private_subnet_2_cidr: ${{ secrets.PRIVATE_SUBNET_2_CIDR }}
      TF_VAR_container_port: ${{ secrets.CONTAINER_PORT }}
      TF_VAR_github_repo: ${{ secrets.REPO_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_identifier: ${{ secrets.DB_IDENTIFIER }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_identifier_username: ${{ secrets.IDENTIFIER_USERNAME }}
      TF_VAR_identifier_password: ${{ secrets.IDENTIFIER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-duration-seconds: 3600

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      #clean code
      - name: Clean Terraform code
        run: terraform fmt -recursive -check=false

      #run terraform init
      - name: Terraform Init
        run: terraform init

      #destroy infrastructure
      - name: Terraform Destroy
        run: |
          aws sts get-caller-identity
          terraform destroy -auto-approve -lock-timeout=5m
